"""Criação das tabelas iniciais

Revision ID: af5846eb2f1e
Revises: 
Create Date: 2025-11-26 12:50:54.733848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5846eb2f1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_cnpj'), 'empresa', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresa_id'), 'empresa', ['id'], unique=False)
    op.create_index(op.f('ix_empresa_nome'), 'empresa', ['nome'], unique=False)
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contato_email'), 'contato', ['email'], unique=False)
    op.create_index(op.f('ix_contato_empresa_id'), 'contato', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_contato_id'), 'contato', ['id'], unique=False)
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contato_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contato.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_contato_id'), 'registro', ['contato_id'], unique=False)
    op.create_index(op.f('ix_registro_data_registro'), 'registro', ['data_registro'], unique=False)
    op.create_index(op.f('ix_registro_id'), 'registro', ['id'], unique=False)
    op.create_index(op.f('ix_registro_usuario_id'), 'registro', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_usuario_id'), table_name='registro')
    op.drop_index(op.f('ix_registro_id'), table_name='registro')
    op.drop_index(op.f('ix_registro_data_registro'), table_name='registro')
    op.drop_index(op.f('ix_registro_contato_id'), table_name='registro')
    op.drop_table('registro')
    op.drop_index(op.f('ix_contato_id'), table_name='contato')
    op.drop_index(op.f('ix_contato_empresa_id'), table_name='contato')
    op.drop_index(op.f('ix_contato_email'), table_name='contato')
    op.drop_table('contato')
    op.drop_index(op.f('ix_empresa_nome'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_id'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_cnpj'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
